from app.expert_system.engine.models import Condition, Rule


# El patrón visual identifica la rama del diagrama. Las condiciones de cultivo
# aumentan o disminuyen la confianza sin cambiar la hipótesis ya identificada.
RULES: tuple[Rule, ...] = (
    Rule(
        id="rust-foliar-pattern",
        disease_id="coffee_rust",
        conditions=(
            Condition("affected_part", "leaf", "Parte afectada: hoja", 1, required=True),
            Condition("leaf_lesions", True, "Manchas o lesiones foliares", 1, required=True),
            Condition("iron_spot_compatible", False, "El patrón no corresponde a mancha de hierro", 1, required=True),
            Condition("orange_powder_underside", True, "Signos de roya, especialmente en el envés", 6, required=True),
            Condition("yellow_spots", True, "Manchas amarillas", 1),
            Condition("humid_conditions", True, "Condiciones húmedas", 1),
            Condition("recent_rains", True, "Lluvias recientes", 1),
            Condition("dense_shade", True, "Sombra densa", 1),
            Condition("poor_air_circulation", True, "Poca aireación", 1),
            Condition("nearby_plants_affected", True, "Síntomas en plantas cercanas", 1),
        ),
    ),
    Rule(
        id="iron-spot-foliar-pattern",
        disease_id="iron_spot",
        conditions=(
            Condition("affected_part", "leaf", "Parte afectada: hoja", 1, required=True),
            Condition("leaf_lesions", True, "Manchas o lesiones foliares", 1, required=True),
            Condition("iron_spot_compatible", True, "Lesiones circulares pardas, con centro claro y halo rojizo o amarillento", 6, required=True),
            Condition("circular_brown_lesions", True, "Lesiones circulares pardas", 1),
            Condition("light_center", True, "Centro claro", 1),
            Condition("yellow_halo", True, "Halo amarillento o rojizo", 1),
            Condition("humid_conditions", True, "Condiciones húmedas", 1),
            Condition("recent_rains", True, "Lluvias recientes", 1),
            Condition("nutritional_stress", True, "Señales de estrés nutricional", 2),
            Condition("nearby_plants_affected", True, "Síntomas en plantas cercanas", 1),
        ),
    ),
    Rule(
        id="american-leaf-spot-pattern",
        disease_id="american_leaf_spot",
        conditions=(
            Condition("affected_part", "leaf", "Parte afectada: hoja", 1, required=True),
            Condition("leaf_lesions", True, "Manchas o lesiones foliares", 1, required=True),
            Condition("iron_spot_compatible", False, "El patrón no corresponde a mancha de hierro", 1, required=True),
            Condition("orange_powder_underside", False, "No presenta signos característicos de roya", 1, required=True),
            Condition("eye_spot_compatible", True, "Lesiones compatibles con ojo de gallo o gotera", 6, required=True),
            Condition("target_like_lesions", True, "Lesiones tipo diana", 1),
            Condition("light_center", True, "Centro claro", 1),
            Condition("dark_margin", True, "Borde oscuro", 1),
            Condition("humid_conditions", True, "Condiciones húmedas", 1),
            Condition("recent_rains", True, "Lluvias recientes", 1),
            Condition("dense_shade", True, "Sombra densa", 1),
            Condition("poor_air_circulation", True, "Poca aireación", 1),
            Condition("nearby_plants_affected", True, "Síntomas en plantas cercanas", 1),
        ),
    ),
    Rule(
        id="stem-necrotic-pattern",
        disease_id="stem_necrotic_disorder",
        conditions=(
            Condition("affected_part", "stem_branch", "Parte afectada: tallo o rama", 1, required=True),
            Condition("stem_path_active", True, "Lesiones visibles o secamiento progresivo", 2, required=True),
            Condition("stem_necrosis", True, "Tejido muerto, necrosis o secamiento localizado", 6, required=True),
            Condition("stem_humid_conditions", True, "Condiciones húmedas", 1),
            Condition("stem_recent_rains", True, "Lluvias recientes", 1),
            Condition("stem_dense_shade", True, "Sombra densa", 1),
            Condition("stem_poor_air_circulation", True, "Poca aireación", 1),
            Condition("stem_damage_distribution", ("scattered", "widespread"), "Daño disperso o extendido", 1),
        ),
    ),
    Rule(
        id="stem-fungal-pattern",
        disease_id="stem_fungal_disorder",
        conditions=(
            Condition("affected_part", "stem_branch", "Parte afectada: tallo o rama", 1, required=True),
            Condition("stem_path_active", True, "Lesiones visibles o secamiento progresivo", 2, required=True),
            Condition("stem_necrosis", False, "Sin necrosis localizada", 1, required=True),
            Condition("stem_fungal_structures", True, "Hilos, micelio u otras estructuras visibles", 6, required=True),
            Condition("stem_humid_conditions", True, "Condiciones húmedas", 1),
            Condition("stem_recent_rains", True, "Lluvias recientes", 1),
            Condition("stem_dense_shade", True, "Sombra densa", 1),
            Condition("stem_poor_air_circulation", True, "Poca aireación", 1),
            Condition("stem_damage_distribution", ("scattered", "widespread"), "Daño disperso o extendido", 1),
        ),
    ),
    Rule(
        id="stem-pest-pattern",
        disease_id="stem_associated_pest",
        conditions=(
            Condition("affected_part", "stem_branch", "Parte afectada: tallo o rama", 1, required=True),
            Condition("stem_path_active", True, "Lesiones visibles o secamiento progresivo", 2, required=True),
            Condition("stem_necrosis", False, "Sin necrosis localizada", 1, required=True),
            Condition("stem_fungal_structures", False, "Sin estructuras fúngicas visibles", 1, required=True),
            Condition("stem_insect_damage", True, "Perforaciones o insectos visibles", 6, required=True),
            Condition("stem_humid_conditions", True, "Condiciones húmedas", 1),
            Condition("stem_recent_rains", True, "Lluvias recientes", 1),
            Condition("stem_dense_shade", True, "Sombra densa", 1),
            Condition("stem_poor_air_circulation", True, "Poca aireación", 1),
            Condition("stem_damage_distribution", ("scattered", "widespread"), "Daño disperso o extendido", 1),
        ),
    ),
    Rule(
        id="stem-unspecified-pattern",
        disease_id="stem_unspecified_disorder",
        conditions=(
            Condition("affected_part", "stem_branch", "Parte afectada: tallo o rama", 1, required=True),
            Condition("stem_path_active", True, "Lesiones visibles o secamiento progresivo", 2, required=True),
            Condition("stem_necrosis", False, "Sin necrosis localizada", 1, required=True),
            Condition("stem_fungal_structures", False, "Sin estructuras fúngicas visibles", 1, required=True),
            Condition("stem_insect_damage", False, "Sin perforaciones o insectos visibles", 6, required=True),
            Condition("stem_humid_conditions", True, "Condiciones húmedas", 1),
            Condition("stem_recent_rains", True, "Lluvias recientes", 1),
            Condition("stem_dense_shade", True, "Sombra densa", 1),
            Condition("stem_poor_air_circulation", True, "Poca aireación", 1),
            Condition("stem_damage_distribution", ("scattered", "widespread"), "Daño disperso o extendido", 1),
        ),
    ),
    Rule(
        id="fruit-disease-pattern",
        disease_id="fruit_associated_disease",
        conditions=(
            Condition("affected_part", "fruit", "Parte afectada: fruto", 1, required=True),
            Condition("fruit_path_active", True, "Lesiones o alteración anormal del fruto", 2, required=True),
            Condition("fruit_necrosis_or_rot", True, "Necrosis, pudrición o hundimiento del tejido", 6, required=True),
            Condition("fruit_development_stage", ("green", "growing", "ripening", "ripe", "dry"), "Etapa del fruto registrada", 1),
            Condition("fruit_humid_conditions", True, "Condiciones húmedas", 1),
            Condition("fruit_recent_rains", True, "Lluvias recientes", 1),
            Condition("fruit_dense_shade", True, "Sombra densa", 1),
            Condition("fruit_damage_distribution", ("scattered", "widespread"), "Daño disperso o extendido", 1),
        ),
    ),
    Rule(
        id="fruit-pest-pattern",
        disease_id="fruit_associated_pest",
        conditions=(
            Condition("affected_part", "fruit", "Parte afectada: fruto", 1, required=True),
            Condition("fruit_path_active", True, "Lesiones o alteración anormal del fruto", 2, required=True),
            Condition("fruit_necrosis_or_rot", False, "Sin necrosis o pudrición visible", 1, required=True),
            Condition("fruit_insect_damage", True, "Perforaciones o signos de alimentación de insectos", 6, required=True),
            Condition("fruit_development_stage", ("green", "growing", "ripening", "ripe", "dry"), "Etapa del fruto registrada", 1),
            Condition("fruit_humid_conditions", True, "Condiciones húmedas", 1),
            Condition("fruit_recent_rains", True, "Lluvias recientes", 1),
            Condition("fruit_dense_shade", True, "Sombra densa", 1),
            Condition("fruit_damage_distribution", ("scattered", "widespread"), "Daño disperso o extendido", 1),
        ),
    ),
    Rule(
        id="fruit-unspecified-pattern",
        disease_id="fruit_unspecified_disorder",
        conditions=(
            Condition("affected_part", "fruit", "Parte afectada: fruto", 1, required=True),
            Condition("fruit_path_active", True, "Lesiones o alteración anormal del fruto", 2, required=True),
            Condition("fruit_necrosis_or_rot", False, "Sin necrosis o pudrición visible", 1, required=True),
            Condition("fruit_insect_damage", False, "Sin perforaciones o signos de insectos", 6, required=True),
            Condition("fruit_development_stage", ("green", "growing", "ripening", "ripe", "dry"), "Etapa del fruto registrada", 1),
            Condition("fruit_humid_conditions", True, "Condiciones húmedas", 1),
            Condition("fruit_recent_rains", True, "Lluvias recientes", 1),
            Condition("fruit_dense_shade", True, "Sombra densa", 1),
            Condition("fruit_damage_distribution", ("scattered", "widespread"), "Daño disperso o extendido", 1),
        ),
    ),
)
